export const copy = {
  uz: {
    nav: ["Bosh sahifa", "Xizmatlar", "Portfolio", "Texnologiyalar", "Biz haqimizda", "Aloqa"],
    cta: "Loyiha boshlash",
    ctaArrow: "Loyiha boshlash",
    portfolioCta: "Portfolio ko‘rish",
    contactCta: "Biz bilan bog‘lanish",
    viewAll: "Barchasini ko‘rish",
    more: "Batafsil",
    viewProject: "Loyihani ko‘rish",
    submit: "So‘rov yuborish",
    heroBadge: "Digital Solutions  •  Web  •  Mobile  •  Automation",
    heroLive: "Engineering studio  ·  Toshkent",
    heroTitle: ["Biznesingiz uchun", "zamonaviy raqamli", "yechimlar yaratamiz"],
    heroText:
      "VITASoft — biznesingizni rivojlantiruvchi web, mobile va custom software yechimlarni yaratadigan texnologik hamkor.",
    stack: ["React", "Next.js", "Node.js", "NestJS", "PostgreSQL", "AI APIs"],
    metrics: [
      ["50+", "Loyihalar"],
      ["30+", "Mamnun mijozlar"],
      ["5+", "Yillik tajriba"],
      ["10+", "Texnologiyalar"],
    ],
    servicesLabel: "Xizmatlarimiz",
    servicesTitle: "Biznesingiz uchun to‘liq raqamli yechimlar",
    servicesText:
      "G‘oyadan tayyor mahsulotgacha — biznesingiz uchun kerak bo‘lgan barcha texnologik yechimlarni ishlab chiqamiz.",
    services: [
      {
        title: "Veb sayt yaratish",
        d: "Tezkor, SEO-ga mos va konversiyaga yo‘naltirilgan korporativ saytlar va landing page’lar.",
        items: ["Korporativ saytlar", "Landing page", "SaaS platformalar", "Web ilovalar"],
      },
      {
        title: "Internet do‘kon",
        d: "To‘lov, ombor va yetkazib berish bilan to‘liq ishlaydigan onlayn savdo platformalari.",
        items: ["Katalog va savat", "To‘lov tizimlari", "Buyurtma boshqaruvi", "Admin panel"],
      },
      {
        title: "CRM tizimlar",
        d: "Sotuv, mijozlar va ichki jarayonlarni bitta tizimda boshqarish uchun custom CRM.",
        items: ["Sotuv voronkasi", "Mijozlar bazasi", "Hisobotlar", "Integratsiyalar"],
      },
      {
        title: "Mobile ilovalar",
        d: "iOS va Android uchun qulay, tezkor va brendingizga mos mobil ilovalar.",
        items: ["React Native", "Flutter", "iOS / Android", "App Store / Play"],
      },
      {
        title: "Telegram botlar",
        d: "Sotuv, qo‘llab-quvvatlash va avtomatlashtirish uchun professional Telegram botlar.",
        items: ["Savdo botlari", "Qo‘llab-quvvatlash", "To‘lov integratsiyasi", "Bildirishnomalar"],
      },
      {
        title: "UI va UX",
        d: "Foydalanuvchi yo‘lini o‘ylab ishlangan, chiroyli va conversion-focused interfeyslar.",
        items: ["UX research", "UI dizayn", "Design system", "Prototip"],
      },
    ],
    aboutLabel: "Biz haqimizda",
    aboutTitle: "Texnologiya — biznesingiz uchun natija berishi kerak",
    aboutText:
      "Biz faqat kod yozmaymiz. Biz biznes muammolarini tahlil qilib, real natija beradigan raqamli mahsulotlar yaratamiz.",
    processLabel: "Qanday ishlaymiz?",
    processTitle: "G‘oyadan tayyor mahsulotgacha",
    processSteps: [
      { title: "Talablarni tahlil qilish", d: "Biznesingizning maqsad va talablarini o‘rganamiz." },
      { title: "Rejalashtirish", d: "Loyiha bosqichlari va muddatlarini belgilaymiz." },
      { title: "UI/UX dizayni", d: "Loyiha dizaynini va interaktiv prototipini ishlab chiqamiz." },
      { title: "Dasturlash", d: "Dastur kodini toza va xalqaro standartlarga muvofiq yozamiz." },
      { title: "Testlash", d: "Tezlik, xavfsizlik va xatolarni to‘liq tekshiramiz." },
      { title: "Ishga tushirish", d: "Tizimni serverga joylashtirib, to‘liq ishga tushiramiz." },
      { title: "Doimiy monitoring", d: "Loyihangizning uzluksiz ishlashini kafolatlaymiz." },
    ],
    portfolioLabel: "Portfolio",
    portfolioTitle: "Biz yaratgan raqamli mahsulotlar",
    techLabel: "Texnologiyalar",
    techTitle: "Zamonaviy texnologiyalar bilan quramiz",
    statsTitle: "Natija — bizning asosiy metriikamiz",
    stats: [
      ["50+", "Tugallangan loyihalar"],
      ["30+", "Mamnun mijozlar"],
      ["5+", "Yillik tajriba"],
      ["95%", "Mijoz mamnunligi"],
      ["24/7", "Texnik qo‘llab-quvvatlash"],
    ],
    testiLabel: "Mijozlar",
    testiTitle: "Mijozlarimiz nima deydi?",
    faqLabel: "FAQ",
    faqTitle: "Ko‘p beriladigan savollar",
    faqText: "Loyiha boshlashdan oldin tez-tez so‘raladigan savollarga javoblar.",
    bandTitle: "G‘oyangizni raqamli mahsulotga aylantiramiz",
    bandText:
      "Loyihangiz haqida gaplashamiz. Mutaxassislarimiz sizga eng optimal texnologik yechimni taklif qiladi.",
    contactLabel: "Aloqa",
    contactTitle: "Keling, loyihangizni muhokama qilamiz",
    contactText: "Loyiha haqida ma’lumot qoldiring, tez orada siz bilan bog‘lanamiz.",
    contactInfo: "To‘g‘ridan-to‘g‘ri bog‘laning",
    contactFollow: "Bizni kuzatib boring",
    contactName: "To‘liq ism",
    contactNamePh: "Ali Aliyev",
    contactService: "Xizmat",
    contactServicePh: "Xizmatni tanlang",
    contactReach: "Siz bilan qanday bog‘lanaylik?",
    contactPhone: "Telefon",
    contactTelegram: "Telegram",
    contactEmail: "Email",
    contactPhoneLabel: "Telefon raqam",
    contactPhonePh: "93 190 80 97",
    contactTgLabel: "Telegram",
    contactTgPh: "@username",
    contactEmailLabel: "Email",
    contactEmailPh: "name@company.com",
    contactMessage: "Xabar",
    contactMessagePh: "Loyihangiz, maqsadlaringiz va kutilayotgan muddatlar haqida yozishingiz mumkin...",
    contactSend: "Xabar yuborish",
    contactPrivacy: "Yuborilgan barcha ma’lumotlar maxfiy saqlanadi va uchinchi shaxslarga berilmaydi.",
    contactServices: [
      "Veb-saytlar yaratish",
      "Internet-do‘konlar",
      "CRM tizimlar",
      "Mobil ilovalar",
      "Telegram bot yaratish",
      "UI / UX dizayn",
      "Boshqa / Aniq emas",
    ],
    contactAddr: "Toshkent, O‘zbekiston · Masofadan",
    footerTag: "Bizneslar uchun zamonaviy va samarali raqamli yechimlar.",
    footerCopy: "© 2026 VITASoft. Barcha huquqlar himoyalangan.",
  },
  ru: {
    nav: ["Главная", "Услуги", "Портфолио", "Технологии", "О нас", "Контакты"],
    cta: "Начать проект",
    ctaArrow: "Начать проект",
    portfolioCta: "Смотреть портфолио",
    contactCta: "Связаться с нами",
    viewAll: "Смотреть все",
    more: "Подробнее",
    viewProject: "Смотреть проект",
    submit: "Отправить заявку",
    heroBadge: "Digital Solutions  •  Web  •  Mobile  •  Automation",
    heroLive: "Engineering studio  ·  Ташкент",
    heroTitle: ["Создаём современные", "цифровые решения", "для вашего бизнеса"],
    heroText:
      "VITASoft — технологический партнёр, который разрабатывает web, mobile и custom software для роста бизнеса.",
    stack: ["React", "Next.js", "Node.js", "NestJS", "PostgreSQL", "AI APIs"],
    metrics: [
      ["50+", "Проекты"],
      ["30+", "Довольные клиенты"],
      ["5+", "Года опыта"],
      ["10+", "Технологии"],
    ],
    servicesLabel: "Услуги",
    servicesTitle: "Полный набор цифровых решений для бизнеса",
    servicesText: "От идеи до готового продукта — разрабатываем все нужные технологические решения.",
    services: [
      {
        title: "Создание сайтов",
        d: "Быстрые, SEO-friendly корпоративные сайты и лендинги, заточенные под конверсию.",
        items: ["Корпоративные сайты", "Лендинги", "SaaS-платформы", "Веб-приложения"],
      },
      {
        title: "Интернет-магазин",
        d: "Онлайн-торговля с оплатой, складом и доставкой в одном контуре.",
        items: ["Каталог и корзина", "Платёжные системы", "Управление заказами", "Админ-панель"],
      },
      {
        title: "CRM-системы",
        d: "Кастомные CRM для продаж, клиентов и внутренних процессов.",
        items: ["Воронка продаж", "База клиентов", "Отчёты", "Интеграции"],
      },
      {
        title: "Мобильные приложения",
        d: "Удобные и быстрые приложения для iOS и Android под ваш бренд.",
        items: ["React Native", "Flutter", "iOS / Android", "App Store / Play"],
      },
      {
        title: "Telegram-боты",
        d: "Профессиональные боты для продаж, поддержки и автоматизации.",
        items: ["Продажи", "Поддержка", "Оплата", "Уведомления"],
      },
      {
        title: "UI и UX",
        d: "Интерфейсы, которые выглядят современно и помогают продавать.",
        items: ["UX-исследование", "UI-дизайн", "Дизайн-система", "Прототип"],
      },
    ],
    aboutLabel: "О нас",
    aboutTitle: "Технологии должны давать результат для бизнеса",
    aboutText:
      "Мы не просто пишем код. Мы анализируем бизнес-задачи и создаём цифровые продукты с реальной отдачей.",
    processLabel: "Как мы работаем?",
    processTitle: "От идеи до готового продукта",
    processSteps: [
      { title: "Анализ требований", d: "Изучаем цели и требования вашего бизнеса." },
      { title: "Планирование", d: "Определяем этапы проекта и сроки." },
      { title: "UI/UX дизайн", d: "Разрабатываем дизайн и интерактивный прототип." },
      { title: "Разработка", d: "Пишем чистый код по международным стандартам." },
      { title: "Тестирование", d: "Проверяем скорость, безопасность и ошибки." },
      { title: "Запуск", d: "Размещаем систему на сервере и полностью запускаем." },
      { title: "Постоянный мониторинг", d: "Гарантируем бесперебойную работу проекта." },
    ],
    portfolioLabel: "Портфолио",
    portfolioTitle: "Цифровые продукты, которые мы создали",
    techLabel: "Технологии",
    techTitle: "Собираем на современном стеке",
    statsTitle: "Результат — наша главная метрика",
    stats: [
      ["50+", "Завершённые проекты"],
      ["30+", "Довольные клиенты"],
      ["5+", "Года опыта"],
      ["95%", "Удовлетворённость клиентов"],
      ["24/7", "Техническая поддержка"],
    ],
    testiLabel: "Клиенты",
    testiTitle: "Что говорят наши клиенты?",
    faqLabel: "FAQ",
    faqTitle: "Частые вопросы",
    faqText: "Ответы на вопросы до старта проекта.",
    bandTitle: "Превратим вашу идею в цифровой продукт",
    bandText: "Обсудим проект. Предложим оптимальное технологическое решение.",
    contactLabel: "Контакты",
    contactTitle: "Давайте обсудим ваш проект",
    contactText: "Оставьте информацию о проекте — мы свяжемся с вами в ближайшее время.",
    contactInfo: "Свяжитесь напрямую",
    contactFollow: "Подписывайтесь",
    contactName: "Полное имя",
    contactNamePh: "Али Алиев",
    contactService: "Услуга",
    contactServicePh: "Выберите услугу",
    contactReach: "Как с вами связаться?",
    contactPhone: "Телефон",
    contactTelegram: "Telegram",
    contactEmail: "Email",
    contactPhoneLabel: "Номер телефона",
    contactPhonePh: "93 190 80 97",
    contactTgLabel: "Telegram",
    contactTgPh: "@username",
    contactEmailLabel: "Email",
    contactEmailPh: "name@company.com",
    contactMessage: "Сообщение",
    contactMessagePh: "Расскажите о проекте, целях и желаемых сроках...",
    contactSend: "Отправить сообщение",
    contactPrivacy: "Все отправленные данные хранятся конфиденциально и не передаются третьим лицам.",
    contactServices: [
      "Создание сайтов",
      "Интернет-магазины",
      "CRM-системы",
      "Мобильные приложения",
      "Создание Telegram-бота",
      "UI / UX дизайн",
      "Другое / Пока не ясно",
    ],
    contactAddr: "Ташкент, Узбекистан · Удалённо",
    footerTag: "Современные цифровые решения для бизнеса.",
    footerCopy: "© 2026 VITASoft. Все права защищены.",
  },
  en: {
    nav: ["Home", "Services", "Portfolio", "Technologies", "About", "Contact"],
    cta: "Start a project",
    ctaArrow: "Start a project",
    portfolioCta: "View portfolio",
    contactCta: "Contact us",
    viewAll: "View all",
    more: "Learn more",
    viewProject: "View project",
    submit: "Send request",
    heroBadge: "Digital Solutions  •  Web  •  Mobile  •  Automation",
    heroLive: "Engineering studio  ·  Tashkent",
    heroTitle: ["We build modern", "digital solutions", "for your business"],
    heroText:
      "VITASoft is the technology partner behind the web, mobile and custom software that grows your company.",
    stack: ["React", "Next.js", "Node.js", "NestJS", "PostgreSQL", "AI APIs"],
    metrics: [
      ["50+", "Projects"],
      ["30+", "Happy clients"],
      ["5+", "Years of experience"],
      ["10+", "Technologies"],
    ],
    servicesLabel: "Services",
    servicesTitle: "Complete digital solutions for your business",
    servicesText: "From idea to shipped product — we build every technical solution your business needs.",
    services: [
      {
        title: "Website development",
        d: "Fast, SEO-ready corporate sites and landing pages built to convert.",
        items: ["Corporate websites", "Landing pages", "SaaS platforms", "Web apps"],
      },
      {
        title: "Online store",
        d: "E-commerce with payments, inventory and delivery in one platform.",
        items: ["Catalog & cart", "Payment systems", "Order management", "Admin panel"],
      },
      {
        title: "CRM systems",
        d: "Custom CRM to manage sales, clients and internal workflows.",
        items: ["Sales pipeline", "Client database", "Reports", "Integrations"],
      },
      {
        title: "Mobile apps",
        d: "Fast, branded iOS and Android apps your customers will actually use.",
        items: ["React Native", "Flutter", "iOS / Android", "App Store / Play"],
      },
      {
        title: "Telegram bots",
        d: "Professional bots for sales, support and day-to-day automation.",
        items: ["Sales bots", "Support", "Payments", "Notifications"],
      },
      {
        title: "UI & UX",
        d: "Interfaces that look refined and are designed around conversion.",
        items: ["UX research", "UI design", "Design system", "Prototype"],
      },
    ],
    aboutLabel: "About",
    aboutTitle: "Technology should produce results for your business",
    aboutText:
      "We do not just write code. We analyze business problems and build digital products that deliver.",
    processLabel: "How we work",
    processTitle: "From idea to finished product",
    processSteps: [
      { title: "Requirements analysis", d: "We study your business goals and requirements." },
      { title: "Planning", d: "We define project phases and timelines." },
      { title: "UI/UX design", d: "We design the product and an interactive prototype." },
      { title: "Development", d: "We write clean code to international standards." },
      { title: "Testing", d: "We fully check speed, security and bugs." },
      { title: "Launch", d: "We deploy the system to the server and go live." },
      { title: "Ongoing monitoring", d: "We keep the project running without interruption." },
    ],
    portfolioLabel: "Portfolio",
    portfolioTitle: "Digital products we have built",
    techLabel: "Technologies",
    techTitle: "We build with a modern stack",
    statsTitle: "Results are our core metric",
    stats: [
      ["50+", "Completed projects"],
      ["30+", "Happy clients"],
      ["5+", "Years of experience"],
      ["95%", "Client satisfaction"],
      ["24/7", "Technical support"],
    ],
    testiLabel: "Clients",
    testiTitle: "What our clients say",
    faqLabel: "FAQ",
    faqTitle: "Frequently asked questions",
    faqText: "Answers to the questions we hear before a project starts.",
    bandTitle: "We turn your idea into a digital product",
    bandText: "Let’s talk about your project. We’ll propose the most effective technical path.",
    contactLabel: "Contact",
    contactTitle: "Let’s talk about your project",
    contactText: "Leave a few details and we’ll get back to you shortly.",
    contactInfo: "Reach us directly",
    contactFollow: "Follow us",
    contactName: "Full name",
    contactNamePh: "Ali Aliyev",
    contactService: "Service",
    contactServicePh: "Select a service",
    contactReach: "How should we reach you?",
    contactPhone: "Phone",
    contactTelegram: "Telegram",
    contactEmail: "Email",
    contactPhoneLabel: "Phone number",
    contactPhonePh: "93 190 80 97",
    contactTgLabel: "Telegram",
    contactTgPh: "@username",
    contactEmailLabel: "Email",
    contactEmailPh: "name@company.com",
    contactMessage: "Message",
    contactMessagePh: "Tell us about the project, goals and expected timeline...",
    contactSend: "Send message",
    contactPrivacy: "All submitted information is kept confidential and is never shared with third parties.",
    contactServices: [
      "Website development",
      "Online stores",
      "CRM systems",
      "Mobile apps",
      "Telegram bot development",
      "UI / UX design",
      "Other / Not sure yet",
    ],
    contactAddr: "Tashkent, Uzbekistan · Remote",
    footerTag: "Modern, effective digital solutions for businesses.",
    footerCopy: "© 2026 VITASoft. All rights reserved.",
  },
} as const;

export type Locale = keyof typeof copy;
